myapp2/config/routes.rb
Rails.application.routes.draw do
  get 'case/index'
  get 'story/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :story
  resources :case

  post 'story/create'

  post 'case/create'

end

myapp2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

myapp2/app/models/case.rb
class Case < ApplicationRecord
end

myapp2/app/models/story.rb
class Story < ApplicationRecord
end

myapp2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

myapp2/app/controllers/story_controller.rb
class StoryController < ApplicationController
  def index
     @stories = Story.all
  end

  def create
     @story = Story.new(params.require(:story).permit(:story))
     @story.save
     redirect_to @story
  end

  def show
     @story = Story.find(params[:id])
  end
  
  def edit
     @story = Story.find(params[:id])
  end
  
  def update 
     @story = Story.find(params[:id])
     if @story.update(params.require(:story).permit(:story))
        redirect_to @story
     else
        render 'edit'
     end
  end

  def destroy
     @story = Story.find(params[:id])
     @story.destroy
  end
end

myapp2/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def new 
  end	
end

myapp2/app/helpers/application_helper.rb
module ApplicationHelper
end

myapp2/app/helpers/case_helper.rb
module CaseHelper
end

myapp2/app/helpers/stories_helper.rb
module StoriesHelper
end

myapp2/app/helpers/story_helper.rb
module StoryHelper
end

myapp2/app/helpers/welcome_helper.rb
module WelcomeHelper
end

myapp2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

myapp2/app/views/story/edit.html.erb
<h1>Edit Story</h1>

<%= form_with(model: @story, local: true) do |form| %>

<p>
  <%= form.label :text %><br>
  <%= form.text_area :story %>
</p>

<p>
  <%= form.submit %>
</p>
<% end %>

<%= link_to 'Back', story_index_path%>

myapp2/app/views/story/index.html.erb
<%= form_with scope:
 :story, url:story_create_path, local: true do |form| %>

<p>
<%= form.label :title %><br>

<%= form.text_area :story %>
</p>

<p>
   <%= form.submit %>
</p>

<% end %>

<div>
<h4>Added Stories</h4>
<hr>
 <% @stories.each do |story| %>
    <p>Your Story<%= story.story %>
<%= link_to 'Edit', edit_story_path(story) %>
<%= link_to 'Delete', story_path(story), method: 
    :delete, data:{confirm: 'Are you sure?'} %>
<% end %>
<p>
</div>

myapp2/app/views/story/show.html.erb
<p>
  <strong> Story </strong>
</p>

<p>
Your Story:
  <%= @story.story%>
</p>
<%= link_to "Back", story_index_path %>